# Generated by Django 6.0 on 2025-12-23 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_addproduct_branch_product_barcode_sale_saleitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[("do'kon xarajatlari", "Do'kon xarajatlari"), ('shaxsiy xarajatlar', 'Shaxsiy xarajatlar'), ('boshqa xarajatlar', 'Boshqa xarajatlar')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('incurred_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='api.branch')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='api.worker')),
            ],
        ),
    ]
