# Generated by Django 6.0 on 2025-12-23 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='items',
            field=models.ManyToManyField(related_name='sales', to='api.saleitem'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_items', to='api.sale'),
        ),
    ]
