# Generated by Django 6.0 on 2025-12-23 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_sale_items_alter_saleitem_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleitem',
            name='sale',
        ),
        migrations.AddField(
            model_name='saleitem',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sale_items', to='api.branch'),
        ),
    ]
