# Generated by Django 6.0 on 2025-12-23 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_saleitem_sale_saleitem_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitem',
            name='c_price_at_sale',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='price_at_sale',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
