# Generated by Django 6.0 on 2025-12-23 09:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_saleitem_c_price_at_sale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='sold_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
