# Generated by Django 6.0 on 2025-12-23 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_saleitem_sold_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='api.worker', verbose_name='Ishchi'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='location',
            field=models.CharField(max_length=255, verbose_name='Manzil'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Filial nomi'),
        ),
        migrations.AlterField(
            model_name='history',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='api.branch', verbose_name='Filial'),
        ),
        migrations.AlterField(
            model_name='history',
            name='change_type',
            field=models.CharField(max_length=50, verbose_name="O'zgarish turi"),
        ),
        migrations.AlterField(
            model_name='history',
            name='changed_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name="O'zgarish vaqti"),
        ),
        migrations.AlterField(
            model_name='history',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='api.product', verbose_name='Mahsulot'),
        ),
        migrations.AlterField(
            model_name='history',
            name='quantity_changed',
            field=models.IntegerField(verbose_name="O'zgargan miqdor"),
        ),
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Shtrixkod'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Sotib olish narxi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Mahsulot nomi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Mavjud miqdor'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Sotish narxi'),
        ),
    ]
