# Generated by Django 6.0 on 2025-12-24 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_history_worker_alter_branch_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleitem',
            name='c_price_at_sale',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='price_at_sale',
        ),
        migrations.AddField(
            model_name='sale',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='sale',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
