# Generated by Django 6.0 on 2025-12-24 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_saleitem_c_price_at_sale_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='items',
        ),
        migrations.AddField(
            model_name='sale',
            name='items',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='api.saleitem'),
            preserve_default=False,
        ),
    ]
