# Generated by Django 6.0 on 2025-12-26 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_sale_items_saleitem_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='branch',
        ),
        migrations.AddField(
            model_name='sale',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
