# Generated by Django 6.0 on 2025-12-26 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_sale_total_amount_remove_saleitem_branch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addproduct',
            name='items',
        ),
        migrations.AddField(
            model_name='addproduct',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api.supplier', verbose_name='Yetkazib beruvchi'),
        ),
        migrations.AddField(
            model_name='addproductitem',
            name='add_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='add_product', to='api.addproduct'),
        ),
        migrations.AddField(
            model_name='addproductitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Sotib olish narxi'),
        ),
        migrations.AlterField(
            model_name='addproduct',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan vaqti"),
        ),
        migrations.AlterField(
            model_name='addproduct',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='add_products', to='api.branch', verbose_name='Filial'),
        ),
        migrations.AlterField(
            model_name='addproduct',
            name='worker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='add_products', to='api.worker', verbose_name='Hodim'),
        ),
        migrations.AlterField(
            model_name='addproductitem',
            name='added_quantity',
            field=models.PositiveIntegerField(verbose_name='Mahsulot miqdori'),
        ),
        migrations.AlterField(
            model_name='addproductitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='add_items', to='api.product', verbose_name='Mahsulot'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='api.branch', verbose_name='Filial'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='debt',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Qarz miqdori'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Izoh'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Ismi'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(max_length=15, verbose_name='Telefon raqami'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Summa'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='api.branch', verbose_name='Filial'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[("do'kon xarajatlari", "Do'kon xarajatlari"), ('shaxsiy xarajatlar', 'Shaxsiy xarajatlar'), ('boshqa xarajatlar', 'Boshqa xarajatlar')], max_length=50, verbose_name='Sababi'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Izoh'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='incurred_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Olish vaqti'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='api.worker', verbose_name='Hodim'),
        ),
        migrations.AlterField(
            model_name='history',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='api.worker', verbose_name='Hodim'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name="To'langan summa"),
        ),
        migrations.AlterField(
            model_name='sale',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='api.branch', verbose_name='Filial'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='api.customer', verbose_name='Qarzdor'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Chegirma'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sold_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Sotish vaqti'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='api.worker', verbose_name='Hodim'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product', verbose_name='Mahsulot'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Miqdor'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='sold_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Sotish vaqti'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='debt',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Qarz miqdori'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Izoh'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Ismi'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone_number',
            field=models.CharField(max_length=15, verbose_name='Telefon raqami'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='api.branch', verbose_name='Filial'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Ismi'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='phone_number',
            field=models.CharField(max_length=15, verbose_name='Telefon raqami'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='position',
            field=models.CharField(max_length=100, verbose_name='Lavozimi'),
        ),
    ]
