# Generated by Django 6.0 on 2025-12-26 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_addproduct_items_addproduct_supplier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='api.branch', verbose_name='Filial'),
        ),
    ]
