# Generated by Django 6.0 on 2025-12-27 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_supplier_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproduct',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api.supplier', verbose_name='Yetkazib beruvchi'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='sale',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.sale'),
            preserve_default=False,
        ),
    ]
