# Generated by Django 6.0 on 2025-12-27 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_addproduct_supplier_alter_saleitem_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproductitem',
            name='add_product',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='add_product', to='api.addproduct'),
            preserve_default=False,
        ),
    ]
