# Generated by Django 6.0 on 2025-12-28 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_addproductitem_add_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='currency',
            field=models.CharField(choices=[('UZS', "So'm"), ('USD', 'Dollar')], default='UZS', max_length=3, verbose_name='Valyuta'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name="To'plam "),
        ),
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ismi')),
                ('surname', models.CharField(max_length=100, verbose_name='Familyasi')),
                ('age', models.CharField(max_length=100, verbose_name='Yoshi')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Telefon raqami')),
                ('invest', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Sarmoya miqdori')),
                ('currency', models.CharField(choices=[('UZS', "So'm"), ('USD', 'Dollar')], default='UZS', max_length=3, verbose_name='Valyuta')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kiritilgan vaqti')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investors', to='api.branch', verbose_name='Filial')),
            ],
        ),
    ]
