# Generated by Django 6.0 on 2025-12-28 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_sale_currency_alter_sale_total_price_investor'),
    ]

    operations = [
        migrations.AddField(
            model_name='addproductitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Jami narx'),
        ),
    ]
