# Generated by Django 6.0 on 2025-12-28 10:43

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_addproductitem_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 1, 1, 0, 0), verbose_name='Kiritilgan vaqti'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplier',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Kiritilgan vaqti'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worker',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 12, 28, 10, 43, 41, 797354, tzinfo=datetime.timezone.utc), verbose_name='Kiritilgan vaqti'),
            preserve_default=False,
        ),
    ]
