# Generated by Django 6.0 on 2025-12-28 12:54

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_customer_created_at_supplier_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addproductitem',
            name='input_quantity',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=12, verbose_name='Kiritilgan miqdor (kg yoki dona)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='base_unit',
            field=models.CharField(choices=[('pcs', 'Dona'), ('kg', 'Kilogramm')], default='pcs', max_length=10, verbose_name='Qabul birligi'),
        ),
        migrations.AddField(
            model_name='product',
            name='kg_to_pcs',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='1 kg nechta dona'),
        ),
        migrations.AlterField(
            model_name='addproductitem',
            name='added_quantity',
            field=models.DecimalField(decimal_places=3, editable=False, max_digits=12, verbose_name='Omborga qo‘shildi (dona)'),
        ),
        migrations.AlterField(
            model_name='addproductitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Jami narx'),
        ),
        migrations.AlterField(
            model_name='history',
            name='quantity_changed',
            field=models.DecimalField(decimal_places=3, max_digits=12, verbose_name="O'zgargan miqdor"),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12, verbose_name='Mavjud miqdor (dona)'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name="To'plam"),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Miqdor'),
        ),
    ]
