# Generated by Django 6.0 on 2025-12-28 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_addproductitem_input_quantity_product_base_unit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(verbose_name='Boshlanish vaqti')),
                ('end_datetime', models.DateTimeField(verbose_name='Tugash vaqti')),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Jami kassa')),
                ('total_discounts', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Jami chegirmalar')),
                ('total_purchase', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Jami sotib olishlar')),
                ('total_debt', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Jami qarzlar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_reports', to='api.branch', verbose_name='Filial')),
            ],
        ),
    ]
