# Generated by Django 6.0 on 2025-12-29 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_dailyreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreport',
            name='end_datetime',
            field=models.DateTimeField(verbose_name='Qachongahca '),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='start_datetime',
            field=models.DateTimeField(verbose_name='Qachondan '),
        ),
        migrations.AlterField(
            model_name='product',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api.branch', verbose_name='Filial'),
        ),
    ]
