# Generated by Django 6.0 on 2025-12-30 12:47

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_dailyreport_end_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproductitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18, verbose_name='Jami narx'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='debt',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=18, verbose_name='Qarz miqdori'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='total_debt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Jami qarzlar'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='total_discounts',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Jami chegirmalar'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='total_purchase',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Jami sotib olishlar'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='total_sales',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Jami kassa'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Summa'),
        ),
        migrations.AlterField(
            model_name='investor',
            name='invest',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=18, verbose_name='Sarmoya miqdori'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=18, verbose_name="To'langan summa"),
        ),
        migrations.AlterField(
            model_name='sale',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=18, verbose_name='Chegirma'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=18, verbose_name="To'plam"),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
        ),
    ]
