"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-g*&%(z6tznw(@x*$&i3ejhm_b298*u9*^bwd=!$f$otoyj!%_d'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'api.apps.ApiConfig',
    "unfold",  # before django.contrib.admin
    "unfold.contrib.filters",  # optional, if special filters are needed
    "unfold.contrib.forms",  # optional, if special form elements are needed
    "unfold.contrib.inlines",  # optional, if special inlines are needed
    "unfold.contrib.import_export",  # optional, if django-import-export package is used
    "unfold.contrib.guardian",  # optional, if django-guardian package is used
    "unfold.contrib.simple_history",
    # 'rest_framework',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# REST_FRAMEWORK = {
#     'DEFAULT_PERMISSION_CLASSES': [
#         'rest_framework.permissions.AllowAny', 
#     ],
#     'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
#     'PAGE_SIZE': 10,
# }


from django.templatetags.static import static
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _

UNFOLD = {
    "SITE_TITLE": "Administration",
    "SITE_HEADER": "Safo",
    "SITE_SUBHEADER": "Buhgalteiya boshqaruvi",
    "SITE_URL": "/",

    "SHOW_HISTORY": True, 
    "SHOW_VIEW_ON_SITE": True, 
    "SHOW_BACK_BUTTON": True,

    "BORDER_RADIUS": "10px",


    # Styles
    "STYLES": [
        lambda request: static("css/styles.css"),
    ],
    "SCRIPTS": [
        lambda request: static("js/scripts.js"),
    ],

    "SIDEBAR": {
        "show_search": True,  
        "show_all_applications": True, 
        "navigation": [
            {
                "separator": True,  # Top border
                "collapsible": False,  # Collapsible group of links
                "items": [
                   
                ],
            },
            {
                "title": _("Adminlar boshqaruvi"),
                "separator": False,
                "collapsible": True, 
                "items": [
                    {
                        "title": _("Adminlar"),
                        "icon": "people",
                        "link": reverse_lazy("admin:auth_user_changelist"),
                        "permission": lambda request: request.user.has_perm("auth.view_user"),
                    },
                    {
                        "title": _("Admin ruxsatlari"),
                        "icon": "folder_supervised",
                        "link": reverse_lazy("admin:auth_group_changelist"),
                        "permission": lambda request: request.user.has_perm("auth.view_group"),
                    },
                ],
            },
            {
                "title": _("Safo "),
                "separator": False,
                "collapsible": False, 
                "items": [
                    {
                        "title": _("Filiallar"),
                        "icon": "store_mall_directory",
                        "link": reverse_lazy("admin:api_branch_changelist"),
                        "permission": lambda request: request.user.has_perm("api.branch_view"),
                    },
                    {
                        "title": _("Sarmoyadorlar"),
                        "icon": "monetization_on",
                        "link": reverse_lazy("admin:api_investor_changelist"),
                        "permission": lambda request: request.user.has_perm("api.investor_view"),
                    },
                    {
                        "title": _("Sotuvlar"),
                        "icon": "point_of_sale",
                        "link": reverse_lazy("admin:api_sale_changelist"),
                        "permission": lambda request: request.user.has_perm("api.sale_view"),
                    },
                    {
                        "title": _("Mahsulotlar ombori"),
                        "icon": "inventory",
                        "link": reverse_lazy("admin:api_product_changelist"),
                        "permission": lambda request: request.user.has_perm("api.product_view"),
                    },
                    {
                        "title": _("Mahsulot qabul qilish"),
                        "icon": "inventory",
                        "link": reverse_lazy("admin:api_addproduct_changelist"),
                        "permission": lambda request: request.user.has_perm("api.addproduct_view"),
                    },
                    {
                        "title": _("Hodimlar"),
                        "icon": "people_alt",
                        "link": reverse_lazy("admin:api_worker_changelist"),
                        "permission": lambda request: request.user.has_perm("api.worker_view"),
                    },
                    {
                        "title": _("Qarzdorlar"),
                        "icon": "people_alt",
                        "link": reverse_lazy("admin:api_customer_changelist"),
                        "permission": lambda request: request.user.has_perm("api.customer_view"),
                    },
                    {
                        "title": _("Yetkazib beruvchilar"),
                        "icon": "people_alt",
                        "link": reverse_lazy("admin:api_supplier_changelist"),
                        "permission": lambda request: request.user.has_perm("api.supplier_view"),
                    },
                    {
                        "title": _("Harajatlar "),
                        "icon": " list",
                        "link": reverse_lazy("admin:api_expense_changelist"),
                        "permission": lambda request: request.user.has_perm("api.expense_view"),
                    },
                    {
                        "title": _("Tarix "),
                        "icon": "list_alt",
                        "link": reverse_lazy("admin:api_history_changelist"),
                        "permission": lambda request: request.user.has_perm("api.history_view"),
                    },
                    {
                        "title": _("Kunlik hisobot"),
                        "icon": "list_alt",
                        "link": reverse_lazy("admin:api_dailyreport_changelist"),
                        "permission": lambda request: request.user.has_perm("api.dailyreport_view"),
                    },
                ],
                
            },
            ],
    },
}


from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]



# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'uz-us'

TIME_ZONE = 'Asia/Tashkent'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
